### ISSUE TITLE
FFI library loading broken with relative paths

### ISSUE THREAD

**Issue by menski** [zeebe-io/zbc-node#16]
This change https://github.com/zeebe-io/zbc-node/commit/e96f9a005fe52822784f12359ce866a2cc63646e#diff-d73144cd7b8063e6d616e913dacf376a breaks the shared object loading.

### Setup

1. create an empty directory
2. install `zbc-node`, i.e. `yarn add zbc-node`
3. try to create a client
    ```
    const { Client } = require('zbc-node')
    var myClient = new Client({bootstrapAddr: '0.0.0.0:51015'})
    ```
4. Error is printed
    ```
    fs.js:660                                                                                                                                                                                             
      return binding.open(pathModule.toNamespacedPath(path),
                 ^

    Error: ENOENT: no such file or directory, open '../../lib/obj/libzbc-linux-amd64.so'
        at Object.fs.openSync (fs.js:660:18)
        at fs.readFileSync (fs.js:565:33)
        at new DynamicLibrary (/tmp/yolo/node_modules/ffi-napi/lib/dynamic_library.js:67:23)
        at Object.Library (/tmp/yolo/node_modules/ffi-napi/lib/library.js:45:14)
        at new FFILib (/tmp/yolo/node_modules/zbc-node/lib/FFILib.js:50:25)
        at new Client (/tmp/yolo/node_modules/zbc-node/lib/Client.js:26:19)
        at Object.<anonymous> (/tmp/yolo/index.js:3:16)
        at Module._compile (internal/modules/cjs/loader.js:654:30)
        at Object.Module._extensions..js (internal/modules/cjs/loader.js:665:10)
        at Module.load (internal/modules/cjs/loader.js:566:32)
    ```

**Comment by menski** [comment]
When I use the job worker example instead of the small script above with the latest release I now get a segmentation fault :crying_cat_face: 

```
$ node index.js                                                                                                                                                                                         
starting client                                                                                                                                                                                         
panic: runtime error: invalid memory address or nil pointer dereference                                                                                                                                 
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x7fa10d27d293]

goroutine 17 [running, locked to thread]:
main.CreateWorkflow(0x2662dc0, 0xb, 0x2662e40, 0x13, 0x7fa10d170386)
        /go/src/github.com/zeebe-io/libzbc/main.go:68 +0xd3
main._cgoexpwrap_79ffe4581f21_CreateWorkflow(0x2662dc0, 0xb, 0x2662e40, 0x13, 0x0)
        _cgo_gotypes.go:97 +0x7e
Aborted (core dumped)   
```

**Comment by jsam** [comment]
I'm trying to reproduce. Can you tell me if it's on metal or in container environment? It looks like it created a client successfully and then when it tries to deploy the workflow it explodes.

**Comment by menski** [comment]
The segfault was caused by a not working broker connect address. We should probably handle this more gracefully but that's another issue.
